name: 'Get Timestamp Action'
description: 'Get the time in the specified time zone'
author: 'boredland'
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  timeZone:
    description: 'linux time zone'
    required: false
    default: 'UTC'
  format:
    description: 'timestamp format'
    required: false
    default: 'YYYY-MM-DD HH:mm:ss'
outputs:
  time:
    description: 'current time'
    value: ${{ steps.time.outputs.value }}
runs:
  using: "composite"
  steps:
    - id: time
      shell: bash
      env:
        TZ: ${{ inputs.timeZone }}
      run: |
        TEMPLATE="${{ inputs.format }}"
        TEMPLATE=${TEMPLATE/YYYY/%Y}
        TEMPLATE=${TEMPLATE/MM/%m}
        TEMPLATE=${TEMPLATE/DD/%d}
        TEMPLATE=${TEMPLATE/HH/%H}
        TEMPLATE=${TEMPLATE/mm/%M}
        TEMPLATE=${TEMPLATE/ss/%S}
        DATE=$(date +"$TEMPLATE")
        echo "value=$DATE" >> $GITHUB_OUTPUT
